"""The 100 pattern hypotheses (Milestone 4 spec §4-10, §21).

DEFINITIONS ONLY — each is a hypothesis with a mandated null model and the
detector primitive it will be tested with. No pattern is assumed to exist.
Phases follow §21: A high-value structures, B mathematical structures,
C biological/process structures, D compound/evolutionary structures.
"""
from __future__ import annotations

from ..schema import PatternRecord, FAMILIES

F = {
    "SEQ": "P1_SEQUENCE", "RAT": "P2_RATIO_SCALE", "GEO": "P3_GEOMETRY",
    "NET": "P4_GRAPH_NETWORK", "FB": "P5_FEEDBACK", "DIS": "P6_DISTRIBUTION",
    "BIO": "P7_BIOLOGICAL", "SIG": "P8_SIGNAL_CIRCUIT",
    "PIP": "P9_TRANSFORMATION_PIPELINE", "SEL": "P10_SELECTION_EVOLUTION",
}


def P(pid, name, family, phase, detector, null, hyp, feat=None, abl="", res="",
      xfer="", min_ev=3, fail=None, eff="MEDIUM", arch="MEDIUM", desc=""):
    return PatternRecord(
        pattern_id=pid, name=name, family=F[family],
        description=desc or hyp[:160],
        computational_hypothesis=hyp,
        measurable_features=feat or [],
        discovery_algorithm=f"primitive:{detector}",
        null_model=null,
        ablation_strategy=abl, restoration_strategy=res, transfer_strategy=xfer,
        minimum_evidence=min_ev, failure_conditions=fail or [
            "detection not significant vs null",
            "ablation has no capability effect beyond floor",
            "effect not specific to target capability",
            "result does not reproduce across seeds"],
        parameter_efficiency=eff, architecture_dependence=arch,
        phase=phase, detector=detector)


PATTERNS: list[PatternRecord] = [
    # ---------------- P001-P010: sequence & numerical structures ----------------
    P("P001", "Fibonacci spacing", "SEQ", "B", "sequence_gaps",
      "random layer-position sets, K=200 (§12)",
      "Functionally related regions may exhibit non-uniform spacing resembling "
      "Fibonacci-like growth; normalized gap distance vs alternatives.",
      ["significant-region positions", "gap sequence", "normalized distance to fib/uniform/geom/power"],
      abl="remove one member, then the whole candidate sequence", res="restore members individually",
      xfer="transfer the functional pathway, not numerical positions", arch="HIGH"),
    P("P002", "Golden ratio", "RAT", "B", "ratio_enrichment",
      "randomly generated ratio samples, K=200",
      "Useful pathways may hold stable activation/width/contribution ratios near phi; "
      "enrichment around 1.618 vs randomized ratios.",
      ["activation magnitude ratios", "branch width ratios", "contribution ratios"],
      abl="ablate regions participating in the ratio", xfer="rebuild normalized ratios in target",
      fail=["ratio count too small for enrichment test", "phi-bin not above null 95%"]),
    P("P003", "Golden-angle spacing", "GEO", "B", "angular_spacing",
      "random direction sets in activation space",
      "Representation directions may distribute information with near-optimal angular separation "
      "(~137.5deg); angular distribution vs random directions.",
      ["pairwise angles of top principal directions"], abl="remove representative subspaces",
      xfer="align discovered subspace geometry", arch="HIGH"),
    P("P004", "Prime spacing", "SEQ", "B", "sequence_gaps",
      "random position sets, K=200",
      "Functional regions may be distributed with irregular/non-periodic (prime-like) spacing.",
      ["positions of significant regions", "gap sequence"], abl="remove prime-spaced candidate regions",
      xfer="transfer normalized relative positions", arch="HIGH"),
    P("P005", "Power-law contribution", "RAT", "B", "magnitude_fits",
      "shuffled contribution magnitudes, K=200",
      "Contribution may concentrate in few regions with many weak ones (heavy tail); "
      "power-law vs exponential/lognormal/uniform fit comparison.",
      ["ranked contribution magnitudes", "tail exponent", "fit R2"],
      abl="remove top contributors individually and collectively", xfer="transfer high-contribution tail",
      eff="HIGH"),
    P("P006", "Exponential depth growth", "RAT", "B", "depth_curve_fits",
      "random contribution-depth permutations",
      "Capability influence may rise/fall approximately exponentially across depth.",
      ["per-layer contribution", "exp fit R2"], abl="remove early/middle/late regions",
      xfer="align relative depth", arch="HIGH"),
    P("P007", "Logarithmic scaling", "RAT", "B", "depth_curve_fits",
      "random contribution-depth permutations",
      "Early layers may contribute rapidly with diminishing later changes (log-like).",
      ["per-layer contribution", "log fit R2"], abl="test depth bands", xfer="map normalized depth bands",
      arch="HIGH"),
    P("P008", "Square-root scaling", "RAT", "B", "depth_curve_fits",
      "random contribution-depth permutations",
      "Contribution may follow sublinear sqrt(depth) scaling.",
      ["per-layer contribution", "sqrt fit R2"], abl="depth-group interventions",
      xfer="match normalized contribution profile", arch="HIGH"),
    P("P009", "Inverse-square decay", "RAT", "B", "distance_decay",
      "randomized interaction-distance pairings",
      "Influence of distant regions may decay ~1/distance^2.",
      ["pairwise interaction strength vs layer distance"], abl="remove long-distance interaction paths",
      xfer="preserve relative interaction-distance structure", arch="HIGH"),
    P("P010", "Geometric progression", "SEQ", "B", "sequence_gaps",
      "random layer-position sets",
      "Pathway importance may change by multiplicative factors across depth.",
      ["contribution rankings", "ratio sequence"], abl="remove one scale level at a time",
      xfer="preserve relative scale ratios", arch="HIGH"),
    # ---------------- P011-P020: recursion & symmetry ----------------
    P("P011", "Arithmetic progression", "SEQ", "B", "sequence_gaps",
      "random position sets, K=200",
      "Functional regions may occur at approximately regular depth intervals.",
      ["significant-region positions", "gap variance"], abl="remove one then all members",
      xfer="map normalized spacing", arch="HIGH"),
    P("P012", "Harmonic series", "RAT", "B", "magnitude_fits",
      "shuffled magnitudes",
      "Importance may follow decreasing 1/n-style contributions.",
      ["ranked contributions vs 1/n fit"], abl="remove dominant early terms",
      xfer="preserve contribution hierarchy"),
    P("P013", "Lucas sequence", "SEQ", "B", "sequence_gaps",
      "random position sets",
      "Alternative recurrence structures (Lucas-like) may explain region spacing.",
      ["positions", "normalized distance to Lucas"], abl="remove candidate sequence members",
      xfer="transfer relational structure", arch="HIGH"),
    P("P014", "Pascal branching", "NET", "D", "branch_counts",
      "random branching-count profiles",
      "Functional combinations may exhibit combinatorial (binomial-like) branching.",
      ["branch counts per level"], abl="remove branch levels", xfer="reconstruct branching structure"),
    P("P015", "Binomial structure", "DIS", "D", "combination_matrix",
      "random pathway combinations",
      "Capability computation may combine independent binary/conditional pathways; "
      "2^k combination coverage.",
      ["pathway combination effects"], abl="remove branches and combinations",
      xfer="transfer the combination rule"),
    P("P016", "Fractal self-similarity", "GEO", "B", "motif_self_similarity",
      "randomized hierarchical graphs",
      "Similar functional motifs may repeat across scales.",
      ["subgraph similarity across depth scales"], abl="remove one motif instance",
      xfer="transfer scale-normalized motif", arch="HIGH"),
    P("P017", "Recursion", "FB", "B", "repeated_signature",
      "random transformation signatures",
      "Capabilities may require repeated application of similar transformations across depth.",
      ["cosine of transformation outputs across layers"], abl="interrupt recurrence at different depths",
      xfer="transfer repeated transformation mechanism", arch="HIGH"),
    P("P018", "Symmetry", "GEO", "B", "symmetry_test",
      "symmetric-label-permuted graphs",
      "Functionally equivalent regions may show symmetric activation/interaction patterns.",
      ["swap-symmetry score of adjacency"], abl="remove one symmetric member",
      xfer="transfer symmetry-preserving structure"),
    P("P019", "Rotational symmetry", "GEO", "B", "subspace_geometry",
      "random rotations of subspaces",
      "Representation subspaces may contain equivalent orientations (rotation-invariant roles).",
      ["PCA subspace principal angles"], abl="remove directions", xfer="align subspaces by rotation",
      arch="HIGH"),
    P("P020", "Reflection symmetry", "GEO", "B", "subspace_geometry",
      "random sign-flipped directions",
      "Opposing representation directions may encode complementary information.",
      ["mirrored direction correlations"], abl="remove one side", xfer="preserve complementary mapping"),
    # ---------------- P021-P040: network/graph (Phase A core) ----------------
    P("P021", "Series connection", "NET", "A", "graph_motifs",
      "random DAG topologies, same node/edge counts",
      "Capabilities may require sequential transformations A->B->C->D with task-dependent flow.",
      ["directed chain paths", "edge task-dependence"], abl="remove chain nodes individually and together",
      res="patch clean activations back along the chain", xfer="transfer the complete functional chain",
      min_ev=4, eff="HIGH"),
    P("P022", "Parallel connection", "NET", "A", "graph_motifs",
      "random DAG topologies",
      "Capabilities may arise from independent parallel branches between shared endpoints.",
      ["edge-disjoint branch sets"], abl="remove each branch", xfer="transfer multiple branches",
      min_ev=4),
    P("P023", "Series-parallel network", "NET", "A", "graph_motifs",
      "random DAG topologies",
      "Real circuits may combine sequential and parallel structure (SP-decomposable motifs).",
      ["series/parallel decomposition"], abl="test each substructure", xfer="transfer motif hierarchy"),
    P("P024", "Convergence (all-roads-to-Rome)", "NET", "A", "graph_motifs",
      "degree-preserving randomized graphs",
      "Multiple pathways may converge on a critical representational region "
      "(high fan-in + high betweenness + task relevance).",
      ["in-degree", "path convergence count", "betweenness", "flow centrality"],
      abl="remove one incoming path; several; the convergence node",
      res="restore incoming paths via activation patching",
      xfer="transfer convergent pathway architecture", min_ev=4, eff="HIGH"),
    P("P025", "Divergence / branching", "NET", "A", "graph_motifs",
      "degree-preserving randomized graphs",
      "One representation may feed multiple specialized pathways (high fan-out).",
      ["out-degree", "child task-relevance"], abl="remove branches one at a time",
      xfer="transfer branch structure", min_ev=4),
    P("P026", "Fan-in combination", "NET", "A", "graph_motifs",
      "degree-preserving randomized graphs",
      "Multiple signals may need to combine (super/additive interaction) before a capability emerges.",
      ["fan-in counts", "pairwise interaction terms"], abl="remove inputs one at a time; pairs",
      xfer="preserve required input set", min_ev=4),
    P("P027", "Feedback loop", "FB", "A", "repeated_signature",
      "random transformation signature pairings",
      "Capabilities may depend on information returning to earlier computation "
      "(repeated/iterative activation relationships).",
      ["cross-depth transformation similarity", "corrective response to perturbation"],
      abl="block candidate recurrence point", res="restore feedback signal",
      xfer="transfer feedback mechanism", arch="HIGH"),
    P("P028", "Feed-forward chain", "NET", "A", "graph_motifs",
      "random DAG topologies",
      "Capabilities may emerge through strictly directional transformations through depth.",
      ["depth-ordered path scores"], abl="break the path at each link", xfer="preserve path ordering",
      min_ev=4),
    P("P029", "Recurrent loop (depth recurrence)", "FB", "B", "repeated_signature",
      "random signature pairings",
      "Repeated computation across depth may be functionally equivalent to recurrence.",
      ["transformation signature repeats"], abl="remove one iteration (layer)",
      xfer="transfer repeated transformation", arch="HIGH"),
    P("P030", "Hub-and-spoke", "NET", "A", "graph_motifs",
      "degree-preserving randomized graphs",
      "One representation may coordinate multiple specialized branches "
      "(disproportionate weighted centrality).",
      ["weighted degree centrality"], abl="remove the hub; then individual spokes",
      xfer="test hub transfer separately from spokes", min_ev=4),
    P("P031", "Mesh network", "NET", "B", "graph_density",
      "random graphs with equivalent node/edge counts",
      "Capabilities may depend on dense interconnection rather than a simple chain.",
      ["edge density", "cross-link counts"], abl="random edges vs structurally important edges",
      xfer="transfer sparse/dense topology"),
    P("P032", "Tree hierarchy", "NET", "B", "hierarchy_detection",
      "random hierarchical graphs",
      "Capabilities may decompose hierarchically (nested clustering of activation pathways).",
      ["dendrogram depth", "module consistency"], abl="remove entire branches", xfer="transfer hierarchy"),
    P("P033", "DAG of transformations", "NET", "B", "graph_motifs",
      "random DAGs",
      "Capability processing can be approximated as a DAG of transformations.",
      ["causal-approximation graph stats"], abl="remove graph cuts", xfer="transfer topology"),
    P("P034", "Small-world network", "NET", "B", "small_world_stats",
      "random graphs with equivalent node/edge counts",
      "Pathways may combine local specialization with a few long-range links "
      "(high clustering, short path length).",
      ["clustering coefficient", "average path length", "small-worldness Q"],
      abl="remove long-range edges", xfer="preserve critical long-range links"),
    P("P035", "Scale-free network", "NET", "B", "degree_distribution",
      "degree-shuffled random graphs",
      "A few regions may hold disproportionately high connectivity (heavy-tailed degree).",
      ["degree distribution fit", "tail exponent"], abl="remove hubs", xfer="transfer hubs vs distributed alt"),
    P("P036", "Community / modular network", "NET", "A", "community_detection",
      "randomized community assignments (label shuffles)",
      "Different capabilities may occupy partially independent functional communities.",
      ["modularity Q", "community task profiles"], abl="remove communities",
      xfer="transfer community modules", min_ev=4),
    P("P037", "Bottleneck", "NET", "A", "graph_motifs",
      "degree-preserving randomized graphs",
      "Capability information may pass through a narrow high-traffic region "
      "(high flow, low width).",
      ["flow through node vs node width", "low-dim high-traffic score"],
      abl="destroy the bottleneck (mask/downscale)", res="restore bottleneck activations",
      xfer="reconstruct bottleneck in target", min_ev=4, eff="HIGH"),
    P("P038", "Bridge / connector", "NET", "A", "graph_motifs",
      "degree-preserving randomized graphs",
      "A few connections may join otherwise separate functional communities "
      "(high edge betweenness).",
      ["edge betweenness", "community-pair linkage"], abl="remove the bridge edge/nodes",
      xfer="transfer bridge relationship", min_ev=4),
    P("P039", "Cut-set / critical separator", "NET", "A", "graph_motifs",
      "random same-size node sets",
      "Several components may jointly form a minimal set whose removal destroys the capability.",
      ["min-cut approximation", "joint ablation effect"], abl="remove candidate cut sets",
      xfer="transfer complete cut-set-associated structure", min_ev=4, eff="HIGH"),
    P("P040", "Redundant parallel paths", "NET", "A", "graph_motifs",
      "random same-size path sets",
      "Robust capabilities may have multiple interchangeable routes "
      "(removing one barely hurts; removing all collapses).",
      ["per-path ablation vs joint ablation"], abl="remove paths individually then together",
      xfer="transfer one or multiple routes", min_ev=4),
    # ---------------- P041-P060: biological / neural organization ----------------
    P("P041", "Neural hierarchy", "BIO", "C", "abstraction_profile",
      "depth-shuffled representation profiles",
      "Capability computation may progress through increasingly abstract representations.",
      ["representation abstraction vs depth (probe decodability)"], abl="remove hierarchical levels",
      xfer="align abstraction stages"),
    P("P042", "Lateral inhibition", "BIO", "C", "anti_correlation",
      "label-shuffled activation pairs",
      "Competition between nearby representations may improve discrimination "
      "(anti-correlated activation groups).",
      ["negative activation correlations"], abl="remove competitive relationships",
      xfer="recreate competition"),
    P("P043", "Excitation/inhibition balance", "BIO", "C", "sign_balance",
      "random sign balances",
      "Useful computation may depend on controlled positive/negative contribution balance.",
      ["positive vs negative contribution mass"], abl="perturb balance (scale +/- branches)",
      xfer="match normalized balance"),
    P("P044", "Sparse coding", "DIS", "A", "sparsity_selectivity",
      "random sparse activation patterns, label shuffles",
      "Capabilities may be represented by sparse, task-selective activation patterns.",
      ["activation sparsity (Hoyer/Gini)", "task selectivity of high-sparse units"],
      abl="remove high-selectivity units", res="restore unit activations from clean run",
      xfer="transfer sparse activation subspace", min_ev=4, eff="HIGH"),
    P("P045", "Distributed representation", "DIS", "A", "distributed_ablation",
      "random subset ablations, size-matched",
      "Capability information may be encoded collectively across many regions; "
      "graceful degradation under random removal.",
      ["degradation curve vs removed fraction"], abl="random subsets of increasing size",
      xfer="transfer representation subspace, not units", min_ev=4),
    P("P046", "Cellular specialization", "BIO", "C", "role_clustering",
      "shuffled role assignments",
      "Different regions may specialize for different computational roles.",
      ["cluster separation of task profiles"], abl="remove clusters", xfer="transfer functional clusters"),
    P("P047", "Functional redundancy", "BIO", "C", "leave_k_out",
      "random removal orderings",
      "Multiple regions can substitute for each other (leave-one-out tolerance).",
      ["LOO effect distribution"], abl="remove members individually", xfer="transfer one member + test"),
    P("P048", "Modularity", "NET", "A", "community_detection",
      "randomized community assignments",
      "Capabilities may consist of semi-independent functional modules.",
      ["within/between module edge ratios", "modularity Q"], abl="remove modules",
      xfer="transfer a module", min_ev=4),
    P("P049", "Hierarchical specialization", "BIO", "C", "hierarchy_detection",
      "shuffled nesting labels",
      "Specialization may occur at multiple levels (nested clusters).",
      ["nested clustering consistency"], abl="test parent and child modules", xfer="transfer hierarchy"),
    P("P050", "Neural ensemble", "BIO", "C", "coactivation_ensemble",
      "random unit sets, size-matched",
      "Capability may depend on coordinated activity of a population, not a single unit.",
      ["coactivation correlation structure", "ensemble vs single-unit effects"],
      abl="remove members individually and collectively", xfer="transfer ensemble representation",
      min_ev=4),
    P("P051", "Population coding", "DIS", "C", "population_decode",
      "label-shuffled decoding (chance)",
      "Information may be represented by the pattern across many units "
      "(linear decodability of the capability).",
      ["cross-validated decoder accuracy vs chance"], abl="remove subsets, param-matched",
      xfer="map population representation", min_ev=3),
    P("P052", "Competitive selection", "SEL", "C", "winner_distribution",
      "random winner assignments",
      "Multiple candidate representations may compete; useful ones dominate on-task.",
      ["winner concentration on-task vs off-task"], abl="remove competitors",
      xfer="transfer selection mechanism"),
    P("P053", "Winner-take-all", "SEL", "C", "activation_concentration",
      "shuffled concentration statistics",
      "Strong capability decisions may depend on sparse winner selection "
      "(activation concentration in few channels).",
      ["top-k activation mass share"], abl="flatten winners (uniformize)", xfer="reconstruct winner mechanism"),
    P("P054", "Cooperative activation", "BIO", "C", "interaction_factorial",
      "random unit pairs",
      "Some units may be weak alone but powerful together (positive factorial interaction).",
      ["interaction = perf(A+B)-perf(A)-perf(B)+base"], abl="single vs group removal",
      xfer="transfer cooperative group", min_ev=4),
    P("P055", "Inhibitory gating", "SIG", "A", "negative_causal",
      "random node sets",
      "Some components may work primarily by suppressing incorrect computation "
      "(ablating them IMPROVES the capability).",
      ["negative ablation deltas"], abl="remove suppression", xfer="transfer gating mechanism",
      min_ev=3),
    P("P056", "Signal amplification", "SIG", "C", "gain_measurement",
      "random amplified node sets",
      "Small relevant signals may be amplified through stages (output gain > 1 along path).",
      ["activation gain per stage"], abl="remove amplifier stages", res="restore stage gain",
      xfer="preserve gain structure"),
    P("P057", "Signal attenuation", "SIG", "C", "gain_measurement",
      "random attenuated sets",
      "Useful reasoning may require suppressing irrelevant information (gain < 1).",
      ["attenuation ratios"], abl="remove attenuation", xfer="transfer filtering mechanism"),
    P("P058", "Synaptic plasticity locus", "BIO", "C", "update_sensitivity",
      "random parameter regions, size-matched",
      "Capability may concentrate in regions most sensitive to small parameter updates.",
      ["|dLoss/dtheta| mass by region"], abl="freeze candidate regions during ft",
      xfer="transfer adaptation dynamics"),
    P("P059", "Hebbian association", "BIO", "C", "coactivation_ensemble",
      "shuffled co-activation pairings",
      "Co-activation relationships may encode reusable associations across tasks.",
      ["stable co-activation across task splits"], abl="break associations (decouple)",
      xfer="transfer relational pattern"),
    P("P060", "Homeostasis", "BIO", "C", "stat_stability",
      "random perturbation baselines",
      "Stable capabilities may depend on maintained activation statistics (normalization).",
      ["activation mean/var stability across inputs"], abl="perturb normalization statistics",
      xfer="match activation statistics"),
    # ---------------- P061-P080: physical / engineering / signal ----------------
    P("P061", "Series resistance", "SIG", "C", "gain_measurement",
      "random stage orderings",
      "Multiple transformations may cumulatively attenuate signal flow.",
      ["cumulative gain along chains"], abl="remove individual stages", xfer="preserve cumulative transform"),
    P("P062", "Parallel resistance", "SIG", "C", "graph_motifs",
      "random topologies",
      "Parallel paths may reduce sensitivity to individual failure.",
      ["robustness under single-path removal"], abl="remove paths", xfer="transfer redundancy"),
    P("P063", "Current splitting", "SIG", "C", "graph_motifs",
      "random topologies",
      "Information may split into several computational channels.",
      ["fan-out with retained information"], abl="remove channels", xfer="transfer split"),
    P("P064", "Current convergence", "SIG", "C", "graph_motifs",
      "random topologies",
      "Multiple information streams may recombine.",
      ["fan-in with information retention"], abl="remove streams", xfer="transfer convergence"),
    P("P065", "Voltage divider", "SIG", "B", "ratio_enrichment",
      "random ratio samples",
      "Representation magnitude may be controlled by stable competing branch ratios.",
      ["branch output ratios"], abl="change branch strengths", xfer="recreate scale relationship"),
    P("P066", "Feedback control", "FB", "C", "corrective_response",
      "open-loop randomizations",
      "Computation may use error signals to correct intermediate representations.",
      ["perturbation -> opposing correction"], abl="disable correction path",
      xfer="transfer controller", arch="HIGH"),
    P("P067", "Negative feedback", "FB", "C", "corrective_response",
      "open-loop randomizations",
      "Stable reasoning may depend on suppressing runaway activations/errors.",
      ["post-perturbation damping"], abl="disable corrective path", xfer="transfer correction"),
    P("P068", "Positive feedback", "FB", "C", "amplification_response",
      "random perturbation directions",
      "Certain representations may reinforce themselves after initial activation.",
      ["post-perturbation amplification"], abl="break reinforcement", xfer="transfer amplification loop"),
    P("P069", "Resonance", "SIG", "B", "repeated_input_response",
      "random input repetition schedules",
      "Representations may respond strongly to repeated/structured compatible inputs.",
      ["response growth under repetition"], abl="remove resonant pathway", xfer="test compatibility"),
    P("P070", "Phase alignment", "SIG", "B", "ordering_perturbation",
      "random orderings",
      "Relative order of transformations may matter beyond component strength.",
      ["order-swap sensitivity"], abl="perturb ordering (swap layer roles)",
      xfer="preserve transformation order", arch="HIGH"),
    P("P071", "Impedance matching", "SIG", "C", "interface_statistics",
      "mismatched-scale insertions",
      "Successful transfer may require matching activation statistics at interfaces.",
      ["source/target activation norm ratios at interfaces"], abl="deliberately mismatch scales",
      xfer="calibrate interface (this IS the alignment step)", min_ev=4),
    P("P072", "Signal filtering", "SIG", "C", "information_survival",
      "random filtering claims",
      "Some regions may function primarily as information filters.",
      ["task-information survival ratio through node"], abl="remove filtering region",
      xfer="transfer filter"),
    P("P073", "Low-pass filtering", "SIG", "B", "frequency_response",
      "random frequency responses",
      "Capabilities may preserve broad structure while removing high-frequency variation.",
      ["perturbation energy survival by band"], abl="remove smoothing behavior",
      xfer="transfer low-frequency representation"),
    P("P074", "High-pass filtering", "SIG", "B", "frequency_response",
      "random frequency responses",
      "Capabilities may depend on retaining fine-grained changes.",
      ["high-band sensitivity"], abl="remove high-frequency-sensitive pathways", xfer="transfer detail pathway"),
    P("P075", "Band-pass filtering", "SIG", "B", "frequency_response",
      "random frequency responses",
      "Capabilities may depend on a specific information scale.",
      ["band-selective sensitivity"], abl="remove selected band", xfer="transfer scale-selective transform"),
    P("P076", "Amplifier chain", "SIG", "C", "gain_measurement",
      "random gain profiles",
      "Weak signals may become useful through sequential amplification.",
      ["gain per depth stage"], abl="remove stages", xfer="transfer gain chain"),
    P("P077", "Representation transformer", "PIP", "B", "mapping_quality",
      "random mappings",
      "A component may transform one representation into another rather than encode answers.",
      ["learned map quality between node representations"], abl="remove transformation",
      xfer="transfer transformation mapping"),
    P("P078", "Bridge circuit (comparison)", "SIG", "C", "difference_operation",
      "random stream pairings",
      "A capability may emerge from comparing/subtracting two representation streams.",
      ["difference-vector predictivity"], abl="remove one side or the comparison",
      xfer="transfer comparison structure"),
    P("P079", "Switch / gating", "SIG", "A", "conditional_activation",
      "label-permuted conditions",
      "Capability pathways may be conditionally activated (input-dependent selection).",
      ["per-condition pathway activation contrast"], abl="force gate open/closed (scale 0 / fixed)",
      xfer="transfer gating policy", min_ev=4),
    P("P080", "Multiplexer / routing", "SIG", "A", "conditional_activation",
      "task-label shuffles",
      "Different tasks may activate different computational routes.",
      ["task-conditional edge weight differences"], abl="disable route", xfer="transfer routing policy",
      min_ev=4),
    # ---------------- P081-P100: transformation, process, evolution ----------------
    P("P081", "Cotton->fiber->thread->fabric pipeline", "PIP", "A", "stage_profile",
      "depth-shuffled stage profiles",
      "A capability may consist of successive transformation stages "
      "(represent->transform->refine->integrate->output) with monotone task-relevance growth.",
      ["stage-wise task relevance", "stage decomposition"], abl="remove one transformation stage",
      xfer="transfer the transformation pipeline", min_ev=4),
    P("P082", "Raw->refined->product", "PIP", "C", "stage_profile",
      "depth-shuffled profiles",
      "Capabilities may progressively refine representations (increasing task relevance).",
      ["relevance slope across stages"], abl="remove refinement stage", xfer="transfer refinement op"),
    P("P083", "Filtering->sorting->assembly", "PIP", "C", "entropy_stages",
      "shuffled stage orders",
      "Computation may first discard irrelevant info, then organize, then combine.",
      ["entropy/selectivity change per stage"], abl="remove each stage", xfer="transfer pipeline"),
    P("P084", "Mining->refining->manufacturing", "PIP", "C", "stage_profile",
      "shuffled profiles",
      "Knowledge may undergo extraction, purification and construction stages.",
      ["extraction/purification/construction signatures"], abl="remove stages", xfer="transfer stages"),
    P("P085", "Seed->plant->fruit", "PIP", "C", "information_expansion",
      "random growth curves",
      "Small initial representations may grow into larger task-specific structures.",
      ["information mass growth across depth"], abl="remove initial seed representation",
      xfer="transfer seed + growth mechanism"),
    P("P086", "Digestion pipeline", "PIP", "C", "decomposition_reconstruction",
      "random decompositions",
      "Complex input may be progressively broken down and recombined.",
      ["decomposition then reconstruction signature"], abl="remove decomposition stages",
      xfer="transfer decomposition pathway"),
    P("P087", "Metabolic pathway", "PIP", "C", "graph_motifs",
      "random path graphs",
      "Capabilities may depend on chains of reusable transformations where intermediates "
      "feed subsequent stages.",
      ["intermediate dependency chain"], abl="remove intermediate reactions", xfer="transfer pathway"),
    P("P088", "Supply chain", "PIP", "C", "dependency_chain",
      "shuffled dependency labels",
      "Different regions may specialize in sequential production of an output.",
      ["supplier->assembler dependency edges"], abl="remove supplier-like nodes",
      xfer="transfer supply-chain stages"),
    P("P089", "Assembly line", "PIP", "C", "stage_profile",
      "shuffled station orders",
      "Layers may act like specialized processing stations.",
      ["per-layer task specialization profile"], abl="remove station", xfer="transfer station function"),
    P("P090", "Quality-control gate", "PIP", "C", "correctness_correlate",
      "label-shuffled correctness",
      "Some components may detect and reject incorrect intermediate representations.",
      ["activation-correctness correlation"], abl="remove gate", xfer="transfer verification mechanism"),
    P("P091", "Fork->process->recombine", "PIP", "A", "graph_motifs",
      "random topologies",
      "Capability may require temporary specialization followed by integration "
      "(diverge then converge).",
      ["diamond motif counts"], abl="remove branch; remove recombination",
      xfer="transfer branch + recombination", min_ev=4),
    P("P092", "Map->route->destination", "PIP", "C", "trajectory_structure",
      "shuffled trajectories",
      "Reasoning may construct an internal route before reaching an answer.",
      ["intermediate-state trajectory structure"], abl="remove intermediate route representation",
      xfer="transfer route mechanism"),
    P("P093", "Multiple paths, common destination", "NET", "A", "graph_motifs",
      "random same-size path sets",
      "Different computational routes may solve the same subproblem.",
      ["alternate successful paths"], abl="remove routes individually",
      xfer="transfer one route or ensemble", min_ev=4),
    P("P094", "Evolution->selection->recombination", "SEL", "D", "recombination_search",
      "random recombinations",
      "Useful circuits may emerge from combining partially useful structures.",
      ["recombination improvement rate"], abl="remove selected components",
      xfer="recombine validated structures", min_ev=5),
    P("P095", "Mutation->selection->retention", "SEL", "D", "evolutionary_search",
      "random mutation acceptance",
      "Search can discover circuits by mutating structures and retaining held-out improvements.",
      ["mutation retention curve"], abl="test selected motif", xfer="transfer evolved motif",
      min_ev=5,
      fail=["evolution run before any validated transfer (standing M3 rule)",
            "selection used held-out data"]),
    P("P096", "Ant-colony path reinforcement", "SEL", "D", "reinforcement_sampling",
      "uniform sampling",
      "Successful routes may become identifiable through repeated performance-based "
      "reinforcement of sampling.",
      ["sampling->success convergence"], abl="remove reinforced path", xfer="transfer high-reward pathway",
      min_ev=5),
    P("P097", "Bee-swarm specialization", "SEL", "C", "role_clustering",
      "shuffled role labels",
      "Regions may specialize in different task roles while cooperating.",
      ["role cluster separation + cooperation terms"], abl="remove specialist group",
      xfer="transfer specialist group"),
    P("P098", "River branching & convergence", "NET", "A", "graph_motifs",
      "random topologies",
      "Information may split into many paths and later reconverge (diamond motifs).",
      ["branch-then-merge motif counts"], abl="remove individual streams",
      xfer="transfer branching-convergence motif", min_ev=4),
    P("P099", "Ecological food web", "NET", "C", "interaction_graph",
      "shuffled interaction signs",
      "Capabilities may arise from interacting modules with competition/cooperation links.",
      ["signed interaction graph structure"], abl="remove modules", xfer="transfer interaction network"),
    P("P100", "Cellular differentiation", "BIO", "C", "specialization_track",
      "depth-shuffled specialization traces",
      "General representations may differentiate into specialized computational roles "
      "across depth/tasks.",
      ["specialization index vs depth"], abl="remove differentiated populations",
      xfer="transfer specialization process"),
]


def all_records() -> list:
    recs = [r.validate() for r in PATTERNS]
    ids = [r.pattern_id for r in recs]
    assert len(ids) == len(set(ids)) == 100, "registry must hold exactly 100 unique patterns"
    return recs


def by_phase(phase: str) -> list:
    return [r for r in all_records() if r.phase == phase]


if __name__ == "__main__":
    recs = all_records()
    from collections import Counter
    print("patterns:", len(recs))
    print("families:", dict(Counter(r.family for r in recs)))
    print("phases:", dict(Counter(r.phase for r in recs)))
